name: Terraform

on:
  push:
    branches: [ "main" ]
  

  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1
      TERRAFORM_VER: 1.5.1 # Same as your Terraform config
      TERRAFORM_PATH: . # this will be path to Terraform file
      
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repository
        uses: actions/checkout@v2

      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: ${{ env.TERRAFORM_VER }}

      - name: terraform init
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform init

      - name: terraform plan
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform plan

      - name: terraform apply
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform apply
          
